# Complex workflow - AFTER actions-maintainer updates  
# Shows updated actions with optimized configurations and migrations

name: Complex CI/CD Pipeline
on: 
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # UPDATED: checkout v4 with optimized settings
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1  # Shallow clone for linting
          fetch-tags: false
      
      # UPDATED: setup-node v4 with built-in caching (no separate cache needed)
      - uses: actions/setup-node@v4
        with:
          node-version: '18'  # Renamed parameter
          cache: 'npm'        # Built-in caching
      
      - run: npm ci
      - run: npm run lint

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: ['16', '18', '20']
    steps:
      # UPDATED: checkout v4
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          fetch-tags: false
      
      # UPDATED: setup-node v4 with built-in caching
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}  # Renamed parameter
          cache: 'npm'                      # Built-in caching eliminates separate cache action
      
      - run: npm ci
      - run: npm test
      
      # UPDATED: upload-artifact v4 with new parameters
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.os }}-${{ matrix.node }}
          path: coverage/
          compression-level: 6  # New parameter for controlling compression
          overwrite: false      # Required explicit setting in v4

  security:
    runs-on: ubuntu-latest
    steps:
      # UPDATED: checkout v4 with full history for security scanning
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0      # Full history needed for security analysis
          fetch-tags: true    # May need tags for version analysis
          
      # UPDATED: CodeQL v3 with improved scanning
      - uses: github/codeql-action/init@v3
        with:
          languages: javascript
          
      # UPDATED: setup-node v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - run: npm ci
      - run: npm run build
      
      # UPDATED: CodeQL analyze v3 (must match init version)
      - uses: github/codeql-action/analyze@v3

  deploy:
    runs-on: ubuntu-latest
    needs: [lint, test, security]
    if: github.ref == 'refs/heads/main'
    steps:
      # UPDATED: checkout v4
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          fetch-tags: false
      
      # UPDATED: download-artifact v4 (must match upload-artifact version)
      - uses: actions/download-artifact@v4
        with:
          name: coverage-ubuntu-latest-18
          path: ./coverage
          
      # MIGRATED: Custom action moved to modern organization with enhanced features
      - uses: modern-org/enhanced-deploy@v2
        with:
          environment: production      # Renamed from 'deploy-env'
          aws-region: us-east-1       # Renamed from 'target-region'
          security-check: true        # New security feature
          compliance-scan: true       # New compliance feature  
          notification-webhook: ${{ secrets.DEPLOY_WEBHOOK }}  # New notification feature
          # REMOVED: legacy-mode (no longer supported)
        env:
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}